# Generated by Django 4.2.15 on 2026-04-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0043_drop_baileys_fields_from_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configinstagram',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='configinstagram',
            name='app_secret',
        ),
        migrations.RemoveField(
            model_name='configmessenger',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='configmessenger',
            name='app_secret',
        ),
        migrations.RemoveField(
            model_name='configmeta',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='configmeta',
            name='app_secret',
        ),
    ]
